[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "picostream"
version = "0.2.0"
dependencies = [
    "numpy",
    "loguru",
    "picosdk",
    "h5py",
    "pyqtgraph",
    "PyQt5",
    "numba",
    "click",
]


[tool.setuptools]
packages = ["picostream"]  # List the package names directly

[project.scripts]
picostream = "picostream.main:main"
